[colors.bright]
black = "#232323"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#d8dee9"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#232323"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#d8dee9"
yellow = "#ebcb8b"

[colors.primary]
background = "#232323"
foreground = "#d8dee9"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.normal]
family = "JetBrainsMono"
style = "Bold"

[scrolling]
history = 100

[window]
opacity = 0.1

[window.padding]
x = 15
y = 15
