#! /bin/bash

sxhkd -c ~/.config/bspwm/themes/bspwm_nord/sxhkd/sxhkdrc &
numlockx &
nitrogen --restore &
picom --config ~/.config/bspwm/themes/bspwm_nord/picom/picom.conf &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/Wallpaper/wall-03.webp
~/.config/bspwm/themes/bspwm_nord/scripts/launch_polybar.sh &

flameshot &
setxkbmap -option "grp:alt_shift_toggle" us,ru

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15

bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d8dee9"
bspc config presel_feedback_color "#2e3440"

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
